spring.datasource.url=jdbc:mysql://localhost:3306/knowgapdb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=123456
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8086
server.error.whitelabel.enabled=false
server.error.path=/error

knowgap.app.jwtSecret=knowgapSecretKeyknowgapSecretKeyknowgapSecretKeyknowgapSecretKey
knowgap.app.jwtExpirationMs=86400000

server.error.include-message=always
server.error.include-binding-errors=always

# Hugging Face chatbot configuration
knowgap.ai.huggingface.token=
knowgap.ai.huggingface.model=mistralai/Mistral-7B-Instruct-v0.2
knowgap.ai.huggingface.url=https://api-inference.huggingface.co/models
