spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/knowgapdb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.driverClassName=${SPRING_DATASOURCE_DRIVER_CLASS_NAME:com.mysql.cj.jdbc.Driver}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:123456}
spring.jpa.database-platform=${SPRING_JPA_DATABASE_PLATFORM:org.hibernate.dialect.MySQLDialect}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=${PORT:8086}
server.error.whitelabel.enabled=false
server.error.path=/error

knowgap.app.jwtSecret=${JWT_SECRET:knowgapSecretKeyknowgapSecretKeyknowgapSecretKeyknowgapSecretKey}
knowgap.app.jwtExpirationMs=86400000

server.error.include-message=always
server.error.include-binding-errors=always

# Hugging Face chatbot configuration
knowgap.ai.huggingface.token=${HF_API_TOKEN:}
knowgap.ai.huggingface.model=${HF_MODEL:mistralai/Mistral-7B-Instruct-v0.2}
knowgap.ai.huggingface.url=${HF_API_URL:https://api-inference.huggingface.co/models}
