spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.driverClassName=${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.database-platform=${SPRING_JPA_DATABASE_PLATFORM}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=${PORT:8086}
server.error.whitelabel.enabled=false
server.error.path=/error

knowgap.app.jwtSecret=${JWT_SECRET:knowgapSecretKeyknowgapSecretKeyknowgapSecretKeyknowgapSecretKey}
knowgap.app.jwtExpirationMs=86400000

server.error.include-message=always
server.error.include-binding-errors=always

# Hugging Face chatbot configuration
knowgap.ai.huggingface.token=${HUGGINGFACE_API_TOKEN:${HF_API_TOKEN:}}
knowgap.ai.huggingface.model=${HUGGINGFACE_MODEL:${HF_MODEL:google/flan-t5-base}}
knowgap.ai.huggingface.url=${HUGGINGFACE_API_URL:${HF_API_URL:https://api-inference.huggingface.co/models}}
